### ISSUE TITLE
  Как сообщить владельцу о проблемах с показаниями датчика?

### ISSUE THREAD

**Issue by yante70** [airalab/sensors.robonomics.network#100]
Гулял я по карте и нашел вот такой датчик - https://sensors.robonomics.network/#/remote/pm10/12/53.150644/38.093499/2131b2b58f1e91b5e7b9dd5df60fb0fc8e5fe7ba17122efff3b4cdd749827d93
  У него показания влажности - 118,99%
  А хозяину приходят какие-то сообщения на этот счет, или с ним уже никак не связаться?

**Comment by tubleronchik** [comment]
На сегодняшний момент у нас не предусмотрены оповещения владельцев датчиков, но подумаем о такой возможночти. Спасибо за информацию и с Новым Годом!

**Comment by yante70** [comment]
> На сегодняшний момент у нас не предусмотрены оповещения владельцев датчиков, но подумаем о такой возможночти. Спасибо за информацию и с Новым Годом!

  На narodmon.ru и на Sensor.community есть рассылка на e-mail...
  например, мне сегодня в 4:55-6:28 ( +2ч ) пришло два письма об отключении/включении датчика - как раз у нас на два часа отключали свет... :)
