### ISSUE TITLE
не корректное отображение карты на айфон

### ISSUE THREAD

**Issue by Leno4ta** [airalab/sensors.robonomics.network#103]
Переодически на карте с айфона видны не все датчики. В Тольятти с айфона я вижу только 5 шт. Также и с жалобами. С айфона не видны жалобы совсем.

**Comment by tubleronchik** [comment]
Какой браузер используется? Только что проверила в Google Chrome и в Safari, отображаются все датчики в Тлт. 
![2F31F219-E12B-4AAF-B1F4-7E3749195AA8](https://user-images.githubusercontent.com/36592446/213400543-7eccef2f-a8dc-4930-a000-b56314b4a651.png)
![7A8CB4EB-26E2-4C00-A74B-611158BFE500](https://user-images.githubusercontent.com/36592446/213400557-453a1c02-214d-4fb6-8806-61fc73131892.png)
