### ISSUE TITLE
Сообщения из чат-бота не видны на карте с айфон 7, айфон 11

### ISSUE THREAD

**Issue by Leno4ta** [airalab/sensors.robonomics.network#104]
с компьютера (на виндоус) видны жалобы и сообщения типо ресайкл. на айфоне видны только датчики.
![photo_2023-03-03_19-17-49](https://user-images.githubusercontent.com/119696864/222757568-bd8ad247-8243-4d10-9780-8fe40bcd90e6.jpg)
![photo_2023-03-03_19-18-13](https://user-images.githubusercontent.com/119696864/222757675-d9ebae9b-990b-4e11-9e5b-83cd1bbf7c54.jpg)

**Comment by vol4tim** [comment]
Воспроизвести данную проблему не получается. она еще актуальная?
