### ISSUE TITLE
Передача в интернет измерений с промышленных газоанализаторов EXIS

### ISSUE THREAD

**Issue by Zachin23** [airalab/sensors.robonomics.network#115]
Для передачи измерений приборов Эксис используется программа Exis Visual Lab
В этой программе предусмотрена передача данных в сети Телеграмм, Viber и ВКонтакте. Кроме этого может быть использована электронная почта и СМС.
Нас интересует Телеграмм и ВКонтакте.
Телеграмм. 
Нужно создать свой бот который будет рассылать полученные данные. У производителя имеется свой бот который можно использовать однако он ненадежен и предлагается создвать собственный.
Кроме того требуется сервер, которого у нас не организовано. И мы хотели бы разместить этот процесс с сервера sensor robonomiks
Вот сообщение полученое от производителя приборов как организовать это. 
"Здравствуйте!
После создания бота вам необходимо узнать у него ID вашей беседы. Нужно подвязать боту обработчик запросов. В нашем случае мы использовали PHP-скрипт, который разместили на хостинге с нашим веб-сайтом. Пример скрипта высылаю во вложении. Замените в нём значение переменной $token на токен вашего бота, выложите на какой-нибудь веб-сервер и откройте в браузере ссылку https://api.telegram.org/bot<TOKEN>/setWebhook?url=<URL>, подставив поля TOKEN и URL (в нашем случае было https://api.telegram.org/bot804369110:AAFC7bFBQs7m7rVlhUuHKOphEpYUnyYYOks/setWebhook?url=https://www.eksis.ru/evl_telegram_bot.php). После этого бот будет отвечать в чате тем самым ID беседы, который и надо указывать в EVL."
"Процесс немного замороченный (хотя может есть и другие пути узнать ID беседы с ботом), но собственный бот необходим - телеграм несколько раз банил наших ботов (видимо, подключение с разных IP из разных географических мест кажется ему подозрительным).

С VK всё проще - разрешите нашей группе на её странице vk отправлять вам сообщения и указывайте в EVL id вашей страницы. Если хотите использовать вашу группу, то укажите в настройках её токен и также разрешите ей отправлять вам сообщения."
Как можно реализовать данный процесс совместно с sensor robonomiks?

**Comment by tubleronchik** [comment]
Добрый день. На данный момент не планируем расширять функционал для поддержки данных датчиков.
