### ISSUE TITLE
Problem with layout on Firefox browser (Ubuntu)

### ISSUE THREAD

**Issue by Fingerling42** [airalab/sensors.robonomics.network#131]
The entire arrangement of elements is broken.

![image](https://github.com/airalab/sensors.robonomics.network/assets/17783902/d8b03759-b224-4546-b36c-64d1c7316cf5)

**Comment by tubleronchik** [comment]
Same on Chrome. Couldn't change to real time as well.
![image](https://github.com/airalab/sensors.robonomics.network/assets/36592446/02e30156-2ca0-42bb-b4fd-63f5475a9ed8)

**Comment by positivecrash** [comment]
fixed in latest PR
