### ISSUE TITLE
Graph visibility

### ISSUE THREAD

**Issue by nakata5321** [airalab/sensors.robonomics.network#134]
When you display more that 1 graph on display and will wait new data values, the map will drop all visible graph to default one.
so from this:
![image](https://github.com/airalab/sensors.robonomics.network/assets/55352168/6b189c04-d199-460b-9516-30e8d5ae18f2)
go to this:
![image](https://github.com/airalab/sensors.robonomics.network/assets/55352168/148d66b4-9c61-41d4-a639-c2534397ddf1)

**Comment by positivecrash** [comment]
fixed in latest PR
