### ISSUE TITLE
GitHub pages integration

### ISSUE THREAD

**Issue by akru** [airalab/sensors.robonomics.network#3]
**Motivation**

Continuous integration using `Actions` and `Pages` looks much more convenient as for developers as for end users.

**Steps**

* [ ] GitHub actions based pages deployment workflow (example: https://github.com/peaceiris/actions-gh-pages#getting-started)
* [ ] Link sensors.robonomics.network to GitHub Pages

**Comment by vol4tim** [comment]
- step actions https://github.com/airalab/sensors.robonomics.network/commit/0387ab7d92bc3462c2599c1d36e23b8a684f17c2
- step link https://github.com/airalab/sensors.robonomics.network/commit/10af39ae095b0f66df9d4b1e1fb802d76606f4f2
