### ISSUE TITLE
Частые провалы в сохранении данных

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#36]
При текущей архитектуре данные регулярно теряются и недоступны в истории.
6.08, около 20:00 пропали данные
![image](https://user-images.githubusercontent.com/77608670/128600891-c596176f-492a-4ef2-a090-815dafbc5ba9.png)

07.08, около 11:35 публичная нода была перезагружена, однако данные за период не сохранились.
![image](https://user-images.githubusercontent.com/77608670/128601156-355cd500-92ef-4c8c-a85e-6ad2ebdb1085.png)

Данные постоянно отслеживаются экологами, поэтому провалы в истории очень неприятны.
![image](https://user-images.githubusercontent.com/77608670/128601205-071c4aa2-654c-42fc-a837-4ace598f36b9.png)

Надо подумать над совершенствованием архитектуры. Что надо сделать? запустить дополнительную ноду? Отправлять данные напрямую в IPCI? Настроить автоматический перезапуск публичной ноды? Нужно решение для повышения надежности.

**Comment by tubleronchik** [comment]
- [ ] Распараллерить потоки

- [ ] Добавить обработку ошибок —исключений (на моменте отправки икстренсика)

- [ ] Сделать описание обработки исключений

- [ ] Менеджер очередей

- [ ] Скрипт с настройкой среды по чистке логов раз в неделю

- [ ] Параллельные потоки логгирования

**Comment by tubleronchik** [comment]
Основные проблемы по сохранению истории устранены. В случае неотправки данных по какой-либо причине, они должны будут появиться через сутки. Неотправленные данные за несколько прошлых дней будут добавлены в ближайшее время.
