### ISSUE TITLE
Не отображается выбранный датчик

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#42]
Новая функция в Истории на карте "Sensor ID (comma separated)" не отображает точки выбранных датчиков. При этом, Сергей делал скринкаст с отображением перемещения датчика Экомобиля. Сейчас этот фокус повторить нельзя. Данные в выгрузке, тем не менее, корректные.

![image](https://user-images.githubusercontent.com/77608670/130396818-6f274d62-f19a-43c3-8578-a81229c7d2ff.png)

**Comment by vol4tim** [comment]
В поле нужно указывать Sensor ID, а на скриншоте видно что указан адрес sender.
Пожалуйста перепроверьте, с правильным Sensor ID.
