### ISSUE TITLE
Интегрировать сенсор VOC

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#43]
Прошу доработать софт наших датчиков для обработки сигналов сенсора VOC. Схема сборки и даташит прилагаются.
[Задачи.docx](https://github.com/airalab/sensors.robonomics.network/files/7038680/default.docx)

**Comment by ip-airalab** [comment]
Данные от датчика уже снимаются прошивкой, но не доходят до карты.
![image](https://user-images.githubusercontent.com/77608670/131631992-96a586c8-6868-47dd-84aa-052961f3fe14.png)
Вот что приходит на карту
{pm10: 19.23, pm25: 4.45, temperature: 30.7, humidity: 14.97, timestamp: 1630479574}

**Comment by tubleronchik** [comment]
Fixed with airalab/sensors-connectivity#43
