### ISSUE TITLE
Недоступны данные за 01.09

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#45]
Выгрузка за 31.08-02.09 показывает отсутствие данных с 31.08.2021 10:02 по 01.09.2021 14:15

![image](https://user-images.githubusercontent.com/77608670/132115836-7fc6477b-9b33-4086-be48-028e735e1b6c.png)

При этом, в этот период горел лес и важно посмотреть показания
![image](https://user-images.githubusercontent.com/77608670/132115893-5ae0934c-721e-4bae-a1ac-a759d7d2b761.png)

**Comment by tubleronchik** [comment]
Не актуально.
