### ISSUE TITLE
Не визуализируются данные

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#49]
При обращении к истории данные читаются и формируются в файл, 
![image](https://user-images.githubusercontent.com/77608670/133985396-e3dfd1c6-e5a1-477a-9e7c-ec2c1c0d0285.png)
![image](https://user-images.githubusercontent.com/77608670/133985329-33001917-d680-4318-bd34-21fd2e67242e.png)

однако на карте не отображаются.
![image](https://user-images.githubusercontent.com/77608670/133985481-ce135951-6706-4b98-be18-672d5407873e.png)

**Comment by tubleronchik** [comment]
Исправлено.
