### ISSUE TITLE
Оптимизировать интерфейс под смартфоны

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#51]
Все больше посетителей на карте пользуются со смартфона, однако различные окна перекрывают друг друга, не позволяя пользоваться сервисом или затрудняя его использование.
![image](https://user-images.githubusercontent.com/77608670/136895960-a2eea476-91ed-475f-8992-479c5e03cc4d.png)
![image](https://user-images.githubusercontent.com/77608670/136895975-6d9334dd-6165-4904-9857-51519d73d99b.png)
![image](https://user-images.githubusercontent.com/77608670/136895985-4623bf64-85e3-46e4-980e-45ccbc06ce4b.png)
![image](https://user-images.githubusercontent.com/77608670/136895989-796b8292-16a4-45a8-ac90-82fe0e205951.png)
![image](https://user-images.githubusercontent.com/77608670/136895995-5d51c09b-f882-4c7d-8ea5-e40ab32b78ff.png)

**Comment by positivecrash** [comment]
done
