### ISSUE TITLE
выгрузка данных с 23/10-29/10

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#54]
По факту данные выгружаются с 23/10 по 25/10 включительно
[23-30.csv](https://github.com/airalab/sensors.robonomics.network/files/7446311/23-30.csv)

**Comment by olga23list** [comment]
А также за эти дни 23/10, 24/10, 25/10 данные, не полные (не все 24 часа), а за несколько часов.

**Comment by tubleronchik** [comment]
Спасибо за информацию, данные подгружаются и станут доступны через несколько часов.
