### ISSUE TITLE
Передача данных на sensor.comunity

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#56]
В нашей прошивке предусмотрено отправление данных на sensor.comunity и некоторые датчики даже отправляют данные, но не все. Мы можем при обновлении прошивки галочки расставить, чтобы отправлять и на общий ресурс?

![image](https://user-images.githubusercontent.com/77608670/141787275-3e3e18f5-7e49-40f5-bb9a-fb959bff84ed.png)

**Comment by yante70** [comment]
У нас все отлично отсылает на sensor.community

**Comment by LoSk-p** [comment]
Отправка на sensor.community по дефолту включена, надо только зарегистрировать датчики там. Но если она до этого была выключена вручную, то только вручную включать в настройках.
