### ISSUE TITLE
Мобильные сенсоры на карте: отобразить след показаний по траектории движения

### ISSUE THREAD

**Issue by ensrationis** [airalab/sensors.robonomics.network#6]
Нужно поддержать реализацию новой опции ["Mobile sensor" для Aira connectivity](https://github.com/airalab/sensors-connectivity/issues/2). Стоит подумать о следе траектории движения, ведь теперь на карте будет не только история показаний от одной и той же точки, но и её трактория изменения gps координат.

**Comment by vol4tim** [comment]
Данный функционал реализован.
