### ISSUE TITLE
выгрузка за 15/01-22/01. не полные данные

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#68]
83f93506e8056e9b5a0992e11dfebeb6318de3a1a262acbc50c2759c4168f9ea - нет данных за 15, 16, 17, 18/01
162ebfac08a69bc96c0bd569c95026c6750cbecca7a61731dfe1a985a9391176 - нет полных данных 15, 16, 17, 18/01
debd6d21b15c8caa69e39a1b82b7e5d515c887af322cb1a356216e5d2283b395 - не полные данные за весь период (3-4 значения за каждый день)
21148bf2bd0830c440e397b7d17af7feab0e5d0469d8f1759e886a1fe7061e80 - не полные данные за весь период (3-4 значения за каждый день)
62436b6ded848ce5c7f4ae62b911b9f9cd61b94a1d62c141822ea756b5121f4a - не полные данные за весь период (3-4 значения за каждый день)
983906f8920eb457a61398eccfbfc2b78657d43629e056a1e410a239a90057ff - за 15,16,17 нет данных. За остальные дни не полные данные
02e11618c450934fc559e4675f47328bd3d0cc347f88fd3e451f8f319b2b6cfa до 21/01 нет данных
0b2d3a247d8088e55bad9c2f368d7f861baa55f5669ebda30c3f0446bbf58580 - не полные данные за весь период (3-4 значения за каждый день)
15cb0549a4c80e75f865c41f9079067b848e4bf2c9ce2258f103449a8b754165 - нет полных данных, много 0 значений
162ebfac08a69bc96c0bd569c95026c6750cbecca7a61731dfe1a985a9391176 - не полные данные за весь период (3-4 значения за каждый день)
217a9ae639e48a9b99de7895c496b224ad6a80f9b679d516557561aedd47c58b - не полные данные за весь период (3-4 значения за каждый день)
245718ba7f94d41270387e905a5631cc79b1fb795df553c0148a82e4de58bbc1 - не полные данные за весь период (3-4 значения за каждый день)
24fd03929ff61d714ce5a2c731d8f5a8f63ee15e35a42d2ed20ba82fa5c966d7 - не полные данные за весь период (3-4 значения за каждый день)
26f97b534a7548218b61ab5ed8b0ba58bc4fe7d8f595220cf05c4439bd29fb68 - не полные данные за весь период (3-4 значения за каждый день)
3554c7216ac8bf1a86c8d7e3b2e55429a94eecb5003f5ca260a11f6279a7a6b0 - не полные данные за весь период (3-4 значения за каждый день)
35c9797b45154048bb004d912906f53d16906b2cb67c0afe9fd33c257688ad57 - не полные данные за весь период (3-4 значения за каждый день)
36ee5f24bb05c884e8de2ed9ecc5092751934b2e208557d2ca36b3f49dd6de08 - не полные данные за весь период (3-4 значения за каждый день)
3ab581da5144c51b050d7c70b6977b82e63e60e675909ef4181f8a9cdbd020c3 - не полные данные за весь период (3-4 значения за каждый день)
450010cb7755e54454cb24bdd81c5a790bc73aaa5844ec53b28b2d3da7744381 - не полные данные за весь период (3-4 значения за каждый день)
48b50ca4b5e0b302cf2bbd24fd7cac0b6a5f627dbed4f4b839beb8a33a0d8da9 - не полные данные за весь период (3-4 значения за каждый день)
5952f954bd7059c417c9ef3ac372180bedd5076d1c09d3d4fe632e7ca2f51d8a - не полные данные за весь период (3-4 значения за каждый день)
5bd528a4d708304254d2417b83f8b5c997ed08ccf956fa4e538fc6cfa40f86c0 - не полные данные за весь период (3-4 значения за каждый день)
6226e5b85b95b488d77742ee6116765f4bf01673b3e7931dbe095e31707aa6a6 - не полные данные за весь период (3-4 значения за каждый день)
6a14b6756422abdb3f67bfe2c2798edbe502dec3c3f8ffaec01c1db72a78a27a - нет данных до 20/01
6d5070d18b59887649aa9510a7fe4fcfa0fbc0a86d734fecd003f41b1846e935 - не полные данные за весь период (3-4 значения за каждый день)
754c187fbff86cd98317b7c310f013a2149894cb4d9156ad7be6ef61620a575a - не полные данные за весь период (3-4 значения за каждый день)
78adf6508f0d0be98baae558f3e9049a0abcd81300f4f3997506f5658c40fff2 - не полные данные за весь период (3-4 значения за каждый день)
7c499116a58e2321efceb71f5f2d6005e06e6b83d8cc2dae40dda07fb283975e - не полные данные за весь период (3-4 значения за каждый день)
7c7ffabc786c46ff40d8ca922b1248e1261baefec702eea160001140063f8c53 - не полные данные за весь период (3-4 значения за каждый день)
7cdeafa03331cb330c3993ff0381457f0713a8fd6d0b3dbe93ea24affe5676ac - не полные данные за весь период (3-4 значения за каждый день) странное единоразовое значение до 2000 
833bbbe8571bddaee0162d7b20f507302c58f849a16726d27fd5b50d11a776e2 - не полные данные. За 16, 20, 21 данных нет 
84ee4d5a45534151de24edb04ac164e6763a8dbd3a99755002d63c2fed2f3e90 - не полные данные. за 21 данных нет
8b96e823cf00fb5c3ae169d9557c9d25805be708848ef2aec43a5bbefcd52352 - данные только за 16 и частично 20
925980020829413ade81da2480d757fcec6975c4e4d31b92e95d653e275275d2 - не полные данные за весь период (3-4 значения за каждый день)
983906f8920eb457a61398eccfbfc2b78657d43629e056a1e410a239a90057ff - нет данных за 15, 16 , 17. За остальные дни не полные
af1dceaf20b84e31b413e9e48752c0384200527c9844002325af2250afca579e - не полные данные за весь период (3-4 значения за каждый день)
c7426039fba119338d4173eb547f9c3245e69b4ffc2cc9f1f0e89f28618e44a1 - нет данных за 15, 16, 17. За остальные дни не полные данные
d40924da8797a8c2c944a6e79eb13cbb7f7ad20a9ada979f0d1c00463d55195d - не полные данные за весь период (3-4 значения за каждый день)
d4a4dbc616245672294ef9f0794de2cfdd439e32fd6c4142a23109c7f5f8e8b8 -  не полные данные за весь период (3-4 значения за каждый день)
debd6d21b15c8caa69e39a1b82b7e5d515c887af322cb1a356216e5d2283b395 - не полные данные за весь период (3-4 значения за каждый день)
ebb4d12c2004c2c0e19f7ff93f5414fbd7d44a8e1a8decc91bd1dd6a88536dd7 - не полные данные за весь период (3-4 значения за каждый день)
eda473476eae6e187957b915a20295546e8241061574f976e763562458828e4c - не полные данные за весь период (3-4 значения за каждый день)
f5cf0ec44b696400af9b280cb5bedc9e10893f5f961159658a218286f8e97372 - не полные данные за весь период (3-4 значения за каждый день)

**Comment by tubleronchik** [comment]
Данные за указанный период доотправлены.
