### ISSUE TITLE
данные 29.01-05.02

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#69]
0b2d3a247d8088e55bad9c2f368d7f861baa55f5669ebda30c3f0446bbf58580 - не полные данные за каждый день выгрузки. 
162ebfac08a69bc96c0bd569c95026c6750cbecca7a61731dfe1a985a9391176 - не полные данные за каждый день выгрузки, перерыв между значениями 5 часов, хотя интервал выгрузки 10 мин
21148bf2bd0830c440e397b7d17af7feab0e5d0469d8f1759e886a1fe7061e80 - не полные данные за эти дни, перерыв между выгрузками каждые 3 часа (заданный интервал -10 мин.)
217a9ae639e48a9b99de7895c496b224ad6a80f9b679d516557561aedd47c58b  - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
245718ba7f94d41270387e905a5631cc79b1fb795df553c0148a82e4de58bbc1 - не полные данные за эти дни
24fd03929ff61d714ce5a2c731d8f5a8f63ee15e35a42d2ed20ba82fa5c966d7 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
26f97b534a7548218b61ab5ed8b0ba58bc4fe7d8f595220cf05c4439bd29fb68 - не полные данные за эти дни, перерыв между выгрузками каждые 5 часов (заданный интервал -10 мин.)
34ac74c096ebd91fc250f9acebb8f339872151dc35ce160f8a41428f38087e84 - нет данных за 29/01, и с 01/02-05/02
35c9797b45154048bb004d912906f53d16906b2cb67c0afe9fd33c257688ad57 - за каждый день 3-5 выгрузок (интервал задан 10мин)
36ee5f24bb05c884e8de2ed9ecc5092751934b2e208557d2ca36b3f49dd6de08 - не полные данные за эти дни, перерыв между выгрузками каждые 5 часов (заданный интервал -10 мин.)
3ab581da5144c51b050d7c70b6977b82e63e60e675909ef4181f8a9cdbd020c3 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
450010cb7755e54454cb24bdd81c5a790bc73aaa5844ec53b28b2d3da7744381 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
5952f954bd7059c417c9ef3ac372180bedd5076d1c09d3d4fe632e7ca2f51d8a - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
5bd528a4d708304254d2417b83f8b5c997ed08ccf956fa4e538fc6cfa40f86c0 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
62436b6ded848ce5c7f4ae62b911b9f9cd61b94a1d62c141822ea756b5121f4a - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
754c187fbff86cd98317b7c310f013a2149894cb4d9156ad7be6ef61620a575a - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
78adf6508f0d0be98baae558f3e9049a0abcd81300f4f3997506f5658c40fff2 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
7b1592fc6fe9a46114f227a262ab259b8413d87957a277c0e5d0176fb2b5513c - не полные данные за эти дни, перерыв между выгрузками каждые 4 часа (заданный интервал -10 мин.)
7c499116a58e2321efceb71f5f2d6005e06e6b83d8cc2dae40dda07fb283975e - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
7c7ffabc786c46ff40d8ca922b1248e1261baefec702eea160001140063f8c53 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
7cdeafa03331cb330c3993ff0381457f0713a8fd6d0b3dbe93ea24affe5676ac - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
83f93506e8056e9b5a0992e11dfebeb6318de3a1a262acbc50c2759c4168f9ea - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
925980020829413ade81da2480d757fcec6975c4e4d31b92e95d653e275275d2 - не полные данные за эти дни, перерыв между выгрузками каждые 5 часов (заданный интервал -10 мин.)
983906f8920eb457a61398eccfbfc2b78657d43629e056a1e410a239a90057ff  - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
d4a4dbc616245672294ef9f0794de2cfdd439e32fd6c4142a23109c7f5f8e8b8 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
debd6d21b15c8caa69e39a1b82b7e5d515c887af322cb1a356216e5d2283b395 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
ebb4d12c2004c2c0e19f7ff93f5414fbd7d44a8e1a8decc91bd1dd6a88536dd7 - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
eda473476eae6e187957b915a20295546e8241061574f976e763562458828e4c - не полные данные за эти дни, перерыв между выгрузками каждые 6 часов (заданный интервал -10 мин.)
f5cf0ec44b696400af9b280cb5bedc9e10893f5f961159658a218286f8e97372 - данные только за 29/01 и 30/01 с интервалом в 2 часа. с 01/02-05/02 данных нет

**Comment by tubleronchik** [comment]
Данные за указанный период доотправлены.
