### ISSUE TITLE
22/01-29/01

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#70]
15cb0549a4c80e75f865c41f9079067b848e4bf2c9ce2258f103449a8b754165 - нулевые данные и только за 22/01 в 24-00
34ac74c096ebd91fc250f9acebb8f339872151dc35ce160f8a41428f38087e84 - данные только 24/01

**Comment by tubleronchik** [comment]
Данные за указанный период доотправлены.
