### ISSUE TITLE
выгрузка с 19/03-25/03

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#73]
78adf6508f0d0be98baae558f3e9049a0abcd81300f4f3997506f5658c40fff2 - данные только за 23/03 и за 24/03
7b1592fc6fe9a46114f227a262ab259b8413d87957a277c0e5d0176fb2b5513c - данные только с 19/03 по 22/03
07caa8e104dd944a73301deb0557ddcd2fc7db1956388c523bda0885b13c1073 - данные только за 24/03

**Comment by tubleronchik** [comment]
Никаких глобальных сбоев в работе сервиса не было, возможны были индивидуальные проблемы с датчиками.
