### ISSUE TITLE
выгрузка данных с 02/04- 08/04

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#76]
78adf6508f0d0be98baae558f3e9049a0abcd81300f4f3997506f5658c40fff2 - данные только за 07/04 и 08/04
652768ac54dac2b73f6cf9c5a3146e895018a067eab6eee226b2f39073d2af5a - данные только за 07/04 и 08/04

**Comment by tubleronchik** [comment]
Не актуально.
