### ISSUE TITLE
выгрузка данных с 30/04 по 06/05 

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#78]
53.529522,49.336323 - нет данных за этот период
53.535931,49.350162 - нет данных за этот период
53.546053,49.361692 - нет данных за этот период
53.524771,49.261517 - нет данных за этот период
53.540750,49.284508 - нет данных за этот период
53.544820,49.323535 - нет данных за этот период

**Comment by tubleronchik** [comment]
Не актуально.
