### ISSUE TITLE
выгрузка данных за любой период

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#83]
нет возможности выкачать данные, даты меняла,
https://sensors.robonomics.network/#/download
периоды тоже (выдает максимальный период  - 7 дней, но и за 7 дней выкачка данных не происходит

![Screenshot_18](https://user-images.githubusercontent.com/92647967/182312521-5b7e0ae1-6628-4c39-8fba-79bb13e62b98.png)

**Comment by vol4tim** [comment]
Ошибку исправил.
https://github.com/airalab/RoSeMAN/commit/8525ebd8ac1769f9d45a7876e4042069bbb07f8b
