### ISSUE TITLE
ошибка на 11 айфоне и макбуке А1466

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#86]
На айфоне 11 (на 8 и 12 все отображается корректно) 

https://user-images.githubusercontent.com/92647967/193406201-864727a1-c6fe-47e3-8296-bee156285c63.MP4

 и макбук A1466 при нажатии на дату реагирует кнопка «ветер». Все остальные кнопки работают правильно.
Можно ли сделать, чтоб режим с датой и видимостью сообщений на карте был по умолчанию?

**Comment by ip-airalab** [comment]
На сяоми - андроид 12 Miui 13, то же самое

**Comment by tubleronchik** [comment]
@vol4tim посмотри, пожалуйста

**Comment by positivecrash** [comment]
done
