### ISSUE TITLE
Не работает отображение графика датчика на карте

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#87]
Не работает отображение графика датчика. Основная часть изображения остается внизу вне поле зрения. Проблема актуальная как для IOS таки и для андроид и только для мобильной версии сайта. Если на телефоне открыть "ПК" то все ок.
С компьютера тоже работает.
Проблемы только с мобильной версией.

https://user-images.githubusercontent.com/92647967/194077383-56065073-ccfa-4796-bd2b-8b9ba26529b8.MP4

**Comment by tubleronchik** [comment]
@vol4tim посмотри, пожалуйста.

**Comment by positivecrash** [comment]
Поправили
