### ISSUE TITLE
Нет кнопки скачать историю

### ISSUE THREAD

**Issue by ip-airalab** [airalab/sensors.robonomics.network#88]
Предлагаю добавить на главную страницу функционал скачивания истории.
вариант 1. Ссылка скачивания за период https://sensors.robonomics.network/#/download размещается в верхней строке.
вариант 2. Ссылка скачивания за выбранную для отображения на странице дату на странице размещается возле календаря в нижней строке (тогда не получится скачать недельный период).

Также предлагаю доработать сервис загрузки истории для скачивания, чтобы можно было выбрать не только период скачивания, но и географию - на основании отображаемого на экране региона. Сам регион уже распознается сервисом (указание на текущий город в верхней строке сайта).
![image](https://user-images.githubusercontent.com/77608670/195094522-0e2582cb-ea27-44d7-ae0b-291cbf7e974c.png)

**Comment by tubleronchik** [comment]
@vol4tim посмотри, пожалуйста.

**Comment by positivecrash** [comment]
Сделали
