### ISSUE TITLE
нет данных по выгрузке с 23.09 по 02.10 

### ISSUE THREAD

**Issue by olga23list** [airalab/sensors.robonomics.network#90]
245718ba7f94d41270387e905a5631cc79b1fb795df553c0148a82e4de58bbc1
5952f954bd7059c417c9ef3ac372180bedd5076d1c09d3d4fe632e7ca2f51d8a
450010cb7755e54454cb24bdd81c5a790bc73aaa5844ec53b28b2d3da7744381 нет данных за 02/10 с 09-46
78adf6508f0d0be98baae558f3e9049a0abcd81300f4f3997506f5658c40fff2 нет данных с 24/09
217a9ae639e48a9b99de7895c496b224ad6a80f9b679d516557561aedd47c58b

**Comment by tubleronchik** [comment]
Попробуйте перезагрузить датчики для их корректной работы.
