### ISSUE TITLE
Объединить населенные пункты, если возможно

### ISSUE THREAD

**Issue by yante70** [airalab/sensors.robonomics.network#92]
У нас в Новороссийске и пригородах установлены датчики, но на разных картах они числятся в разных населенных пунктах - Гайдук, Глебовское, Южная Озерейка, Большие Хутора, Мысхако, и др.
  Но на самом деле это пригороды Новороссийска, и хотелось бы видеть из "в городе", а не перелистывать кучу "населенных пунктов"...
  Вот еще карта https://data.airtube.info/table.php?source=&country=RU&city= , к которой можно добавить название "наших"  населенных пунктов, и она покажет информацию по датчикам. установленных в каждом из них...
Novorossiysk
Myskhako
Yuzhnaya+Ozereevka
Glebovskoe
Gaiduk
Bol'shie+Khutora

  Да. у вас ни сайте список этих пунктов можно найти по ссылке https://sensors.robonomics.network/#/download

  С уважением, Ян, Новороссийск

PS: Да. кстати, а вот Борисовка почему-то не выделилась, хотя около нее находится свалка, куда возится мусор со всего города, и там установлено больше всего датчиков - https://data.airtube.info/?pos=44.7126470342417,37.69392013549805,12 ( привожу именно эту карту, т.к. на ней видны не только ваши датчики, но и другие, которые мы ставим... )

**Comment by vol4tim** [comment]
Подумаем, как это можно будет сделать.

**Comment by yante70** [comment]
Получается что-то?

**Comment by yante70** [comment]
Хотелось бы узнать, насколько продвинулось решение моего вопроса...
  Мысхако, Борисовка и Ю.Озерейка - это все небольшие ( до 10тыс ) населенные пункты вокруг Новороссийска. И хотелось бы, чтобы они НЕ были отдельно...
  Или чтобы была возможность качать их либо отдельно, либо в составе нашего Города...

**Comment by yante70** [comment]
А тут пока тишина...
  Напоминаю, что Борисовка, Владимировка, Глебовское, Мысхако, Южная Озерейка - это все пригороды Новороссийска, и их не обязательно выводить как отдельные населенные пункты :)

**Comment by vol4tim** [comment]
Все датчики, из этих населенных пунктов, объединили с Новороссийском.

**Comment by yante70** [comment]
Спасибо, позже гляну...
