### ISSUE TITLE
Выбор городов в ночной теме

### ISSUE THREAD

**Issue by yante70** [airalab/sensors.robonomics.network#94]
Я вижу, сменили интерфейс, и даже попробовал "ночную схему"
  Так вот попробуйте и вы, выбрав "ночную схему" нажать на кнопку "скачать историю" и попробовать выбрать Город.
  Ну что, видно названия городов? :)

**Comment by positivecrash** [comment]
<img width="628" alt="image" src="https://github.com/airalab/sensors.robonomics.network/assets/10559916/b4a14b3d-6d92-4d93-80d6-36bc5654b9e6">

выбор названий городов при скачивании истории - это ваша настройка устройства. Пришлите, пожалуйста, скриншот, если городов не видно

**Comment by tubleronchik** [comment]
@positivecrash у меня такая же проблема. 

![issue](https://github.com/airalab/sensors.robonomics.network/assets/36592446/5cc8c17d-8a30-433a-abf9-268cd0456071)

**Comment by positivecrash** [comment]
@tubleronchik какая ОС и браузер?

**Comment by tubleronchik** [comment]
@positivecrash Ubuntu 20.04, Chrome & Brave. В Firefox все ок

**Comment by yante70** [comment]
Я бы не сказал, что в FireFox все ОК, но получше, чем в Хроме,,,

**Comment by positivecrash** [comment]
> Я бы не сказал, что в FireFox все ОК, но получше, чем в Хроме,,,
> Хотя нет, то же самое - я в первый раз смотрел на своем компе по удаленке, а сейчас глянул уже будучи дома - нет разницы...
> Скрины нужны?

Скрины пока не нужны, спасибо! Проверьте, пожалуйста, теперь города должны быть видны

**Comment by yante70** [comment]
> 

  Вопрос видимости городов при ночной схеме - снимается...
  Но остается вопрос объединения наших пригородов - см. другую тему... :)

**Comment by positivecrash** [comment]
> Вопрос видимости городов при ночной схеме - снимается...
> Но остается вопрос объединения наших пригородов - см. другую тему... :)

супер, спасибо за ваше участие! По объединению городов мой коллега смотрит, я тут не могу ничего сказать :)

**Comment by yante70** [comment]
> > Вопрос видимости городов при ночной схеме - снимается...
> > Но остается вопрос объединения наших пригородов - см. другую тему... :)
> 
> супер, спасибо за ваше участие! По объединению городов мой коллега смотрит, я тут не могу ничего сказать :)

  Что-то ваш коллеги долго смотрит...
