### ISSUE TITLE
Как нужно настроить чужие датчики, чтобы они могли слать данные на sensors.robonomics.network

### ISSUE THREAD

**Issue by yante70** [airalab/sensors.robonomics.network#98]
У меня есть датчик не вашей сборки, который шлет данные на sensor.community
  Как нужно в нем прописать ваши настройки, чтобы он мог слать данные и на ваш сайт?
  Спасибо

**Comment by tubleronchik** [comment]
Привет. Подскажите, пожалуйста, какой датчик используется.

**Comment by yante70** [comment]
Ну, датчики-то стандартные - РМ25/РМ10 и температура/влажность, я имел ввиду сборку...
  Сборки у нас две разные - Тольятти ( шлет данные на свой сайт и на Сенсор.Комунити ) и Краснодар ( только на последний )
  И вот вопрос - что нужно добавить в Краснодар, чтобы он добавился на карте Тольятти?

**Comment by tubleronchik** [comment]
Привет!
В теории можно добавить наш адрес (например сервер [2.connectivity.robonomics.network](http://2.connectivity.robonomics.network/), порт 65). На картинке показан пример добавления нашего сервера в оригинальную прошивку.
![image](https://user-images.githubusercontent.com/36592446/217223928-dd037112-181d-4c4d-89d3-11d99b439815.png)

Но тогда должен быть подключен датчик gps, тк оригинальная прошивка, в отличии от нашей, не позволяет вписать координаты GPS через интерфейс. Кроме того, наша прошивка меняет сервера, то есть в случае проблем с одним, данные будут передаваться на дргугие доступные сервера.
Если перепрошивать, то вот инструкция. С этой прошивкой данные также будут отправляться на [sensor.community](http://sensor.community/) https://wiki.robonomics.network/docs/sensor-setup/#requirements.
